- name: Provision Master
  hosts: master
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

- name: Provision Workers
  hosts: workers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes